WIP
vmware-tanzu/sources-for-knative pull request #416
Opened 2022-04-11 09:33 UTC by embano1

Signed-off-by: Michael Gasch <mgasch@vmware.com>

Fixes #

## Proposed Changes

-
-
-

### Pre-review Checklist

- [ ] **At least 80% unit test coverage**
- [ ] **E2E tests** for any new behavior
- [ ] **Docs** for any user-facing impact

**Release Note**

```release-note

```

2022-07-05 08:38 UTC, embano1 commented on samples/horizon/horizon-source.yml
> +  address: https://10.197.79.54 # horizon.jarvis.tanzu
remove

2022-07-05 16:30 UTC, gabo1208 requested changes

2022-07-05 16:30 UTC, gabo1208 commented on samples/horizon/README.md
> +Finally, deploy the `HorizonSource`.
This trailing spaces and I think is good to go

2022-07-05 16:30 UTC, gabo1208 commented on samples/horizon/README.md
> +Modify the `horizon-source.yml` according to your environment.
.

2022-07-06 00:14 UTC, gabo1208 approved these changes

2022-07-06 00:30 UTC, merged